name: Build and Deploy nopwd website
on:
  push:
    branches:
      - main

jobs:
  deploy-ci:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout Repository
        uses: actions/checkout@main

      - name: â¬‡ï¸ Installing dependencies
        run: npm i

      - name: â¬‡ï¸ Building nopwd website
        run: npm run build
        env:
          GITHUB_SHA: ${{ GITHUB_SHA }}

      - name: ðŸ“¥ Installing firebase command tool
        run: sudo npm install -g firebase-tools

      - name: ðŸ¤« building glcoud credential.json
        run: echo ${{ secrets.DEPLOYMENT_KEY }} | base64 --decode > ./credential.json

      - name: ðŸ“¦ deploy nopwd.rocks
        run: |
          firebase use --add nopwdio
          firebase target:apply hosting rocks nopwd-rocks
          firebase deploy --only hosting:rocks
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./credential.json

      - name: ðŸ¤« removing credential.json
        run: rm ./credential.json
